spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      default_batch_fetch_size: 100
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true



